[package]
name = "toytorrent-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
rand = "0.8.5"
serde = { version = "1.0.192", features = ["derive"] }
sha1 = "0.10.6"
